name: PullPreview

on:
  pull_request:
    types: [ labeled, unlabeled, synchronize, closed, reopened ]

jobs:
  deploy-staging-environment:
    permissions:
      contents: read # to fetch code (actions/checkout)
      deployments: write # to delete deployments
      pull-requests: write # to remove labels
      statuses: write # to create commit status

    name: Deploy PullPreview staging environment
    uses: cybex-gmbh/github-workflows/.github/workflows/pullpreview.yml@main
    with:
      PULLPREVIEW_ADMINS: jheusinger, gael-connan-cybex, holyfabi, lupinitylabs, mszulik
    secrets:
      ENV_VARS: |
        A_DOTENV_VARIABLE="${{ secrets.A_REPOSITORY_SECRET }}"
        ANOTHER_DOTENV_VARIABLE="${{ secrets.AN_ORGANIZATION_SECRET }}"
      PULLPREVIEW_AWS_ACCESS_KEY_ID: ${{ secrets.PULLPREVIEW_AWS_ACCESS_KEY_ID }}
      PULLPREVIEW_AWS_SECRET_ACCESS_KEY: ${{ secrets.PULLPREVIEW_AWS_SECRET_ACCESS_KEY }}

