name: Check out a branch of an external repo.

on:
  workflow_call:
    inputs:
      repository:
        description: The repo to check out.
        required: true
        default: "@collaborators/push"
        type: string
      branch:
        description: The branch to check out.
        required: true
        default: "@collaborators/push"
        type: string

jobs:
  create-branch:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read # to fetch code (actions/checkout)
      pull-requests: write # to remove labels
      statuses: write # to create commit status

    steps:
      - name: Checkout GitHub repository
        if: ${{ contains(github.event.pull_request.labels.*.name, 'differ') && github.event.action != 'unlabeled' && github.event.action != 'closed' }}
        # https://github.com/actions/checkout
        uses: actions/checkout@v4
        with:
          repository: "${{ inputs.repository }}"
          ref: "${{ inputs.branch }}"

      - name: Create branch
        run: |
          git config --global --add safe.directory $(realpath .)
          git checkout -b "${{ inputs.branch }}"
          git commit "inital commit"
          git push
